if ("${frankx_ROOT}" STREQUAL "")
    message("frankx_ROOT not set")
    SET(frankx_FOUND "No")
else()
    set(frankx_INCLUDE_DIRS "${frankx_ROOT}/include")
    message(frankx_INCLUDE_DIRS:${frankx_INCLUDE_DIRS})
    set(frankx_LIB_PATHS "${frankx_ROOT}/lib")
    FIND_LIBRARY(frankx_LIBRARY frankx ${frankx_LIB_PATHS})
    FIND_LIBRARY(movex_LIBRARY movex ${frankx_LIB_PATHS})
    FIND_LIBRARY(ruckig_LIBRARY ruckig ${frankx_LIB_PATHS})
    SET(frankx_LIBRARIES
            "${frankx_LIBRARY}"
            "${movex_LIBRARY}"
            "${ruckig_LIBRARY}")
    if (NOT ${frankx_INCLUDE_DIRS} STREQUAL "")
        SET(frankx_FOUND "YES")
    else()
        SET(frankx_Found "No")
    endif ()
endif()